In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
import lightgbm as lgb
from lightgbm import LGBMRegressor

In [2]:
## featured data from parquet file 

featured_PATH = (
    Path.cwd().parent
    / "data"
    / "processed"
    / "featured_data.parquet"
)
data = pd.read_parquet(featured_PATH)

data

,date,consumption,year,month,day,weekday,national_temp,hour,consumption_lag_24,consumption_lag_48,...,CDD,temp_lag_24,temp_lag_48,temp_rolling_mean_24,yearly_baseline,target_ratio,day_length,is_dark,hour_to_sunrise,is_covid
0,2017-01-01 00:00:00+03:00,27223.06,2017,1,1,Sunday,1.314326,0,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,9.383333,1,8.166667,0
1,2017-01-01 01:00:00+03:00,25825.90,2017,1,1,Sunday,0.719622,1,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,9.383333,1,7.166667,0
2,2017-01-01 02:00:00+03:00,24252.68,2017,1,1,Sunday,0.304513,2,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,9.383333,1,6.166667,0
3,2017-01-01 03:00:00+03:00,22915.47,2017,1,1,Sunday,-0.786601,3,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,9.383333,1,5.166667,0
4,2017-01-01 04:00:00+03:00,22356.99,2017,1,1,Sunday,-0.671492,4,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,9.383333,1,4.166667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84691,2026-08-30 19:00:00+03:00,43487.20,2026,8,30,Sunday,25.720893,19,46146.69,50946.09,...,9.720893,23.592781,23.277993,21.967974,40589.056963,1.071402,13.166667,0,NaN,0
84692,2026-08-30 20:00:00+03:00,44306.44,2026,8,30,Sunday,24.377825,20,46276.80,50700.57,...,8.377825,22.749788,22.444577,21.980691,40588.471465,1.091602,13.166667,1,10.233333,0
84693,2026-08-30 21:00:00+03:00,43046.39,2026,8,30,Sunday,24.069101,21,44800.31,49012.85,...,8.069101,22.351889,21.814356,22.003089,40587.751648,1.060576,13.166667,1,9.233333,0
84694,2026-08-30 22:00:00+03:00,41560.60,2026,8,30,Sunday,23.356092,22,42736.17,47010.37,...,7.356092,21.627122,20.642315,22.044122,40586.758430,1.023994,13.166667,1,8.233333,0
84695,2026-08-30 23:00:00+03:00,39981.85,2026,8,30,Sunday,22.659284,23,41077.36,44980.58,...,6.659284,21.090516,20.430317,22.071631,40585.700163,0.985122,13.166667,1,7.233333,0

In [3]:
# Check NaN 

data.isna().sum()

# Traget variable is target_ratio thus it can not contain NaN
# Thus the first 8789 lines shoul be dropped. The remaining NaN are in hours_to_sunrise which are daylight data.

data = data.dropna(subset=["target_ratio"])
data.isna().sum()

date                                0
consumption                         0
year                                0
month                               0
day                                 0
weekday                             0
national_temp                       0
hour                                0
consumption_lag_24                  0
consumption_lag_48                  0
consumption_lag_168                 0
consumption_rolling_mean_24         0
consumption_rolling_mean_168        0
is_weekend                          0
DoW                                 0
DoY                                 0
is_religious_holiday                0
is_arife                            0
is_national_holiday                 0
is_kopru                            0
bayram_day_index                    0
HDD                                 0
CDD                                 0
temp_lag_24                         0
temp_lag_48                         0
temp_rolling_mean_24                0
yearly_baseline                     0
target_ratio                        0
day_length                          0
is_dark                             0
hour_to_sunrise                 38788
is_covid                            0
dtype: int64

In [4]:
# ---------Train-Val-Test Split-------------

#---Split the data train val test---
train = data[data["date"] < "2024-09-01"].copy()
val   = data[(data["date"] >= "2024-09-01") & (data["date"] < "2025-09-01")].copy()
test  = data[data["date"] >= "2025-09-01"].copy()
print(len(train), len(val), len(test))


exclude_cols = ["date", "weekday", "consumption", "target_ratio", "day"]
feature_cols = [col for col in data.columns if col not in exclude_cols]

categorical_cols = ["hour", "DoW", "bayram_day_index", "DoY", "month"]


X_train, y_train = train[feature_cols], train["target_ratio"]
X_val, y_val = val[feature_cols], val["target_ratio"]

for col in categorical_cols:
    X_train[col] = X_train[col].astype("category")
    X_val[col] = X_val[col].astype("category")

58411 8760 8736

C:\Users\Sultan Selin\AppData\Local\Temp\ipykernel_7924\3773287743.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype("category")
C:\Users\Sultan Selin\AppData\Local\Temp\ipykernel_7924\3773287743.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_val[col] = X_val[col].astype("category")

In [5]:
# -------- LightGBM Model -------------#
model = LGBMRegressor(
    objective = "regression",
    random_state=42,
    importance_type="gain",
    max_bin = 400 #to address DoY(366)
)

model.fit(X_train, y_train, categorical_feature=categorical_cols)
importance_gain = pd.Series(model.feature_importances_, index=feature_cols).sort_values(ascending=False)###
importance_df = importance_gain.reset_index()
importance_df.columns = ["feature", "gain"]
importance_df

c:\Users\Sultan Selin\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\Sultan Selin\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Users\Sultan Selin\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Sultan Selin\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\Sultan Selin\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003785 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5889
[LightGBM] [Info] Number of data points in the train set: 58411, number of used features: 27
[LightGBM] [Info] Start training from score 1.013554

                         feature         gain
0            consumption_lag_168  4106.926012
1             consumption_lag_24  1652.832910
2                yearly_baseline   606.668796
3                            DoY   421.517196
4           is_religious_holiday   300.585488
5                            DoW   186.537745
6                     is_weekend   152.395557
7                           hour    91.008007
8                            CDD    73.707648
9                       is_arife    33.313139
10                 national_temp    23.840363
11            consumption_lag_48    22.462314
12                   temp_lag_24    16.348688
13           is_national_holiday    10.329408
14          temp_rolling_mean_24     7.045192
15              bayram_day_index     6.405990
16               hour_to_sunrise     6.340672
17                      is_covid     3.989327
18                           HDD     3.163590
19  consumption_rolling_mean_168     1.570340
20                    day_length     1.052552
21   consumption_rolling_mean_24     0.893317
22                         month     0.832530
23                          year     0.571976
24                       is_dark     0.247771
25                   temp_lag_48     0.088252
26                      is_kopru     0.000000

In [6]:
# ------Consumption calc over target ratio ----------#

predicted_ratio = model.predict(X_val)
predicted_consumption = predicted_ratio * val["yearly_baseline"]

MAPE = ((val["consumption"] - predicted_consumption).abs() / val["consumption"]).mean() * 100
print("LightGBM Val MAPE (%):", MAPE)


val_copy = val.copy()
val_copy["predicted_consumption"] = predicted_consumption
val_copy["abs_pct_error"] = ((val_copy["consumption"] - val_copy["predicted_consumption"]).abs() / val_copy["consumption"]) * 100

print("Hourly MAPE:", val_copy.groupby("hour")["abs_pct_error"].mean())

LightGBM Val MAPE (%): 4.219217380827702
Hourly MAPE: hour
0     4.456849
1     4.302535
2     4.049599
3     3.943476
4     3.938350
5     4.019800
6     4.005238
7     4.385392
8     4.744401
9     4.561368
10    4.530170
11    4.549686
12    4.488376
13    4.610115
14    4.741077
15    4.727863
16    4.550162
17    4.150584
18    3.679498
19    3.607258
20    3.591884
21    3.799092
22    3.865406
23    3.963039
Name: abs_pct_error, dtype: float64

In [7]:
predicted_ratio_train_v1 = model.predict(X_train)
predicted_consumption_train= predicted_ratio_train_v1 * train["yearly_baseline"]

MAPE_train = ((train["consumption"] - predicted_consumption_train).abs() / train["consumption"]).mean() * 100
print("LightGBM Train_v1 MAPE (%):", MAPE_train)

LightGBM Train_v1 MAPE (%): 1.217843901909221

In [8]:
print("Weekday MAPE:", val_copy.groupby("weekday")["abs_pct_error"].mean())

Weekday MAPE: weekday
Friday       4.095173
Monday       4.722314
Saturday     4.265625
Sunday       5.355654
Thursday     3.778365
Tuesday      3.594666
Wednesday    3.700869
Name: abs_pct_error, dtype: float64

In [9]:
##############--------- Model Version 2 ---------##############
# Drop some features based on importance gain, redundancy and relevancy

drop_features = ["month", "year", "is_dark", "temp_lag_48", "consumption_rolling_mean_24"]

feature_cols_v2 = [c for c in feature_cols if c not in drop_features]
categorical_cols_v2 = [c for c in categorical_cols if c not in drop_features]

X_train_v2 = X_train[feature_cols_v2]
X_val_v2 = X_val[feature_cols_v2]

model_v2 = LGBMRegressor(
    objective= "regression",
    random_state= 42,
    importance_type= "gain",
    max_bin = 400
)

model_v2.fit(X_train_v2, y_train, categorical_feature=categorical_cols_v2)

predicted_ratio_v2 = model_v2.predict(X_val_v2)
predicted_consumption_v2 = predicted_ratio_v2*val["yearly_baseline"]


MAPE_v2 = ((val["consumption"] - predicted_consumption_v2).abs() / val["consumption"]).mean() * 100
print("LightGBM v2 Val MAPE (%):", MAPE_v2)

importance_gain_v2 = pd.Series(model_v2.feature_importances_, index=feature_cols_v2).sort_values(ascending=False)
importance_df = importance_gain_v2.reset_index()
importance_df.columns = ["feature", "gain"]
importance_df

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005117 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5066
[LightGBM] [Info] Number of data points in the train set: 58411, number of used features: 22
[LightGBM] [Info] Start training from score 1.013554
LightGBM v2 Val MAPE (%): 4.230689785466259

                         feature         gain
0            consumption_lag_168  4110.522816
1             consumption_lag_24  1649.958693
2                yearly_baseline   605.787531
3                            DoY   423.364884
4           is_religious_holiday   299.596216
5                            DoW   189.205955
6                     is_weekend   150.413865
7                           hour    89.368772
8                            CDD    73.401346
9                       is_arife    34.436653
10                 national_temp    25.283087
11            consumption_lag_48    21.645965
12                   temp_lag_24    16.440088
13           is_national_holiday     9.651608
14          temp_rolling_mean_24     8.437512
15               hour_to_sunrise     7.575849
16              bayram_day_index     6.750189
17                      is_covid     3.881947
18                           HDD     3.137564
19  consumption_rolling_mean_168     1.706449
20                    day_length     1.238029
21                      is_kopru     0.000000

In [10]:
predicted_ratio_train_v2 = model_v2.predict(X_train_v2)
predicted_consumption_train_v2= predicted_ratio_train_v2 * train["yearly_baseline"]

MAPE_train = ((train["consumption"] - predicted_consumption_train_v2).abs() / train["consumption"]).mean() * 100
print("LightGBM Train_v2 MAPE (%):", MAPE_train)

LightGBM Train_v2 MAPE (%): 1.2105512073076201

In [11]:
##############--------- Model Version 3 ---------##############
# Drop some features based on importance gain, redundancy and relevancy
drop_features_v3 = ["is_kopru", "day_length", "consumption_rolling_mean_168"]

feature_cols_v3 = [c for c in feature_cols_v2 if c not in drop_features_v3]
categorical_cols_v3 = [c for c in categorical_cols_v2 if c not in drop_features_v3]

X_train_v3 = X_train[feature_cols_v3]
X_val_v3 = X_val[feature_cols_v3]

model_v3 = LGBMRegressor(
    objective="regression",
    random_state=42,
    importance_type="gain",
    max_bin = 400
)
model_v3.fit(X_train_v3, y_train, categorical_feature=categorical_cols_v3)

predicted_ratio_v3 = model_v3.predict(X_val_v3)
predicted_consumption_v3 = predicted_ratio_v3 * val["yearly_baseline"]

MAPE_v3 = ((val["consumption"] - predicted_consumption_v3).abs() / val["consumption"]).mean() * 100
print("LightGBM v3 Val MAPE (%):", MAPE_v3)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002244 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4412
[LightGBM] [Info] Number of data points in the train set: 58411, number of used features: 19
[LightGBM] [Info] Start training from score 1.013554
LightGBM v3 Val MAPE (%): 4.101010239913978

In [12]:
predicted_ratio_train_v3 = model_v3.predict(X_train_v3)
predicted_consumption_train_v3 = predicted_ratio_train_v3 * train["yearly_baseline"]

MAPE_train = ((train["consumption"] - predicted_consumption_train_v3).abs() / train["consumption"]).mean() * 100
print("LightGBM Train MAPE (%):", MAPE_train)

LightGBM Train MAPE (%): 1.2208908804417702

In [29]:
##########--------------HYPERPARAMETER TUNING--------------##########

import optuna

def objective(trial):
    params = {
        "objective": "regression",
        "random_state": 42,
        "verbose": -1,
        "n_estimators": trial.suggest_int("n_estimators", 200, 2000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "num_leaves": trial.suggest_int("num_leaves", 15, 80),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_child_samples": trial.suggest_int("min_child_samples", 50, 300),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "subsample_freq": trial.suggest_int("subsample_freq", 1, 7),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
        "max_bin": trial.suggest_int("max_bin", 255, 500),
    }

    model = LGBMRegressor(**params)
    model.fit(X_train_v3, y_train, categorical_feature=categorical_cols_v3)

    # evaluate in consumption space
    predicted_ratio = model.predict(X_val_v3)
    predicted_consumption = predicted_ratio * val["yearly_baseline"]
    return ((val["consumption"] - predicted_consumption).abs() / val["consumption"]).mean() * 100

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50)

print("Best MAPE:", study.best_value)
print("Best params:", study.best_params)

[I 2026-10-01 18:27:13,690] A new study created in memory with name: no-name-5bd84e2b-4ab5-4958-a024-5c9826b121be
[I 2026-10-01 18:27:16,408] Trial 0 finished with value: 3.3988548849266396 and parameters: {'n_estimators': 385, 'learning_rate': 0.24837100260005374, 'num_leaves': 34, 'max_depth': 9, 'min_child_samples': 75, 'colsample_bytree': 0.5314171679977959, 'subsample': 0.8950398219352051, 'subsample_freq': 5, 'reg_alpha': 0.00996941010607, 'reg_lambda': 3.152572230099697e-05, 'max_bin': 450}. Best is trial 0 with value: 3.3988548849266396.
[I 2026-10-01 18:27:18,779] Trial 1 finished with value: 3.8207583481132454 and parameters: {'n_estimators': 269, 'learning_rate': 0.0734379936899741, 'num_leaves': 67, 'max_depth': 5, 'min_child_samples': 222, 'colsample_bytree': 0.7361377484520375, 'subsample': 0.9703510755151576, 'subsample_freq': 1, 'reg_alpha': 2.269359063846955, 'reg_lambda': 0.6941480763039936, 'max_bin': 426}. Best is trial 0 with value: 3.3988548849266396.
[I 2026-10-01 18:27:32,121] Trial 2 finished with value: 3.3942465595340985 and parameters: {'n_estimators': 1564, 'learning_rate': 0.10212553778272118, 'num_leaves': 29, 'max_depth': 9, 'min_child_samples': 209, 'colsample_bytree': 0.5581886558473041, 'subsample': 0.8413343142277885, 'subsample_freq': 2, 'reg_alpha': 0.004024937731211645, 'reg_lambda': 0.1042585149023918, 'max_bin': 413}. Best is trial 2 with value: 3.3942465595340985.
[I 2026-10-01 18:27:44,284] Trial 3 finished with value: 3.1693421073435655 and parameters: {'n_estimators': 1610, 'learning_rate': 0.01731267006874495, 'num_leaves': 78, 'max_depth': 6, 'min_child_samples': 125, 'colsample_bytree': 0.5039028194373714, 'subsample': 0.68864313656141, 'subsample_freq': 3, 'reg_alpha': 2.3309822228589258e-05, 'reg_lambda': 7.653313641301957e-08, 'max_bin': 426}. Best is trial 3 with value: 3.1693421073435655.
[I 2026-10-01 18:27:45,922] Trial 4 finished with value: 4.041767962586605 and parameters: {'n_estimators': 203, 'learning_rate': 0.06161966668573644, 'num_leaves': 21, 'max_depth': 9, 'min_child_samples': 107, 'colsample_bytree': 0.7094577137069127, 'subsample': 0.9249966165300363, 'subsample_freq': 7, 'reg_alpha': 9.264392290422684, 'reg_lambda': 0.1098599290907639, 'max_bin': 442}. Best is trial 3 with value: 3.1693421073435655.
[I 2026-10-01 18:27:52,347] Trial 5 finished with value: 3.2372742501281486 and parameters: {'n_estimators': 708, 'learning_rate': 0.22018543900198947, 'num_leaves': 62, 'max_depth': 12, 'min_child_samples': 166, 'colsample_bytree': 0.8365308459713587, 'subsample': 0.5832089836170435, 'subsample_freq': 6, 'reg_alpha': 1.4941825468163352e-06, 'reg_lambda': 0.02998859909419729, 'max_bin': 354}. Best is trial 3 with value: 3.1693421073435655.
[I 2026-10-01 18:28:00,716] Trial 6 finished with value: 3.1808692269156715 and parameters: {'n_estimators': 1651, 'learning_rate': 0.2228710676751998, 'num_leaves': 79, 'max_depth': 5, 'min_child_samples': 101, 'colsample_bytree': 0.7507409266308182, 'subsample': 0.6087454762889076, 'subsample_freq': 5, 'reg_alpha': 0.003033797990642838, 'reg_lambda': 9.453716933341038e-05, 'max_bin': 481}. Best is trial 3 with value: 3.1693421073435655.
[I 2026-10-01 18:28:04,181] Trial 7 finished with value: 3.919371801987342 and parameters: {'n_estimators': 389, 'learning_rate': 0.018206304980726642, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 133, 'colsample_bytree': 0.5997341537876396, 'subsample': 0.6421182054376322, 'subsample_freq': 4, 'reg_alpha': 0.026116758539624217, 'reg_lambda': 5.426081290497596e-05, 'max_bin': 429}. Best is trial 3 with value: 3.1693421073435655.
[I 2026-10-01 18:28:12,358] Trial 8 finished with value: 3.700553316241939 and parameters: {'n_estimators': 1464, 'learning_rate': 0.08203683030045411, 'num_leaves': 25, 'max_depth': 6, 'min_child_samples': 65, 'colsample_bytree': 0.8128071570419915, 'subsample': 0.7568606769630336, 'subsample_freq': 5, 'reg_alpha': 1.6352128603897818, 'reg_lambda': 6.181591602990356, 'max_bin': 412}. Best is trial 3 with value: 3.1693421073435655.
[I 2026-10-01 18:28:14,383] Trial 9 finished with value: 2.919485122730832 and parameters: {'n_estimators': 813, 'learning_rate': 0.07420147247657288, 'num_leaves': 47, 'max_depth': 3, 'min_child_samples': 66, 'colsample_bytree': 0.6520737037218487, 'subsample': 0.5369837226967138, 'subsample_freq': 1, 'reg_alpha': 0.001877106197286048, 'reg_lambda': 0.12086070524768504, 'max_bin': 354}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:17,593] Trial 10 finished with value: 3.1171025240038905 and parameters: {'n_estimators': 938, 'learning_rate': 0.19765636749952506, 'num_leaves': 62, 'max_depth': 4, 'min_child_samples': 108, 'colsample_bytree': 0.7606352399607157, 'subsample': 0.7314985701448876, 'subsample_freq': 4, 'reg_alpha': 1.0581855736114125e-06, 'reg_lambda': 0.6574244070136497, 'max_bin': 326}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:18,719] Trial 11 finished with value: 4.2004638720440575 and parameters: {'n_estimators': 498, 'learning_rate': 0.019581964490485295, 'num_leaves': 46, 'max_depth': 3, 'min_child_samples': 92, 'colsample_bytree': 0.641118048025318, 'subsample': 0.6499885184088587, 'subsample_freq': 1, 'reg_alpha': 0.0007054418130954131, 'reg_lambda': 0.20712714657507586, 'max_bin': 345}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:20,124] Trial 12 finished with value: 3.7211432065395145 and parameters: {'n_estimators': 494, 'learning_rate': 0.05024923224672922, 'num_leaves': 57, 'max_depth': 3, 'min_child_samples': 60, 'colsample_bytree': 0.7896247719930765, 'subsample': 0.8552761675301951, 'subsample_freq': 2, 'reg_alpha': 6.718289916348321e-05, 'reg_lambda': 0.02431302480334063, 'max_bin': 349}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:22,916] Trial 13 finished with value: 3.1669477363572263 and parameters: {'n_estimators': 825, 'learning_rate': 0.11711328499608943, 'num_leaves': 49, 'max_depth': 5, 'min_child_samples': 128, 'colsample_bytree': 0.6559987970142672, 'subsample': 0.5769403936602897, 'subsample_freq': 1, 'reg_alpha': 0.000576988822264644, 'reg_lambda': 0.0012914708638989757, 'max_bin': 279}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:25,850] Trial 14 finished with value: 3.103536818890416 and parameters: {'n_estimators': 830, 'learning_rate': 0.22781168566081403, 'num_leaves': 53, 'max_depth': 4, 'min_child_samples': 66, 'colsample_bytree': 0.7076447171174065, 'subsample': 0.5254189677546965, 'subsample_freq': 4, 'reg_alpha': 0.0031583556243976398, 'reg_lambda': 0.03573153771355366, 'max_bin': 328}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:27,585] Trial 15 finished with value: 3.054294002916879 and parameters: {'n_estimators': 503, 'learning_rate': 0.15886358982803495, 'num_leaves': 52, 'max_depth': 4, 'min_child_samples': 58, 'colsample_bytree': 0.7288073269137724, 'subsample': 0.5116061278224981, 'subsample_freq': 4, 'reg_alpha': 1.9966423274266594e-06, 'reg_lambda': 0.21073443771955389, 'max_bin': 315}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:29,805] Trial 16 finished with value: 3.4768011659195914 and parameters: {'n_estimators': 381, 'learning_rate': 0.09770234577764297, 'num_leaves': 52, 'max_depth': 4, 'min_child_samples': 92, 'colsample_bytree': 0.641699893167237, 'subsample': 0.5179117377639215, 'subsample_freq': 2, 'reg_alpha': 0.024813008206069107, 'reg_lambda': 0.0010982804217197462, 'max_bin': 399}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:31,657] Trial 17 finished with value: 3.2963251964678064 and parameters: {'n_estimators': 410, 'learning_rate': 0.1422039673237467, 'num_leaves': 45, 'max_depth': 4, 'min_child_samples': 70, 'colsample_bytree': 0.5918854828517934, 'subsample': 0.5463714064472811, 'subsample_freq': 3, 'reg_alpha': 1.404114018221405e-07, 'reg_lambda': 0.006609076857357288, 'max_bin': 262}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:32,552] Trial 18 finished with value: 3.7553096853080032 and parameters: {'n_estimators': 292, 'learning_rate': 0.06182881750495146, 'num_leaves': 35, 'max_depth': 3, 'min_child_samples': 55, 'colsample_bytree': 0.8048075213399826, 'subsample': 0.5743559347877699, 'subsample_freq': 7, 'reg_alpha': 6.003138094703074e-08, 'reg_lambda': 0.20084945065676751, 'max_bin': 317}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:38,941] Trial 19 finished with value: 3.2407275439973753 and parameters: {'n_estimators': 742, 'learning_rate': 0.0793647682981727, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 81, 'colsample_bytree': 0.7829887562051048, 'subsample': 0.5114334376879378, 'subsample_freq': 4, 'reg_alpha': 1.1472965753686793e-07, 'reg_lambda': 0.004091535639877993, 'max_bin': 360}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:40,143] Trial 20 finished with value: 3.445111264409897 and parameters: {'n_estimators': 472, 'learning_rate': 0.1941091473467774, 'num_leaves': 43, 'max_depth': 3, 'min_child_samples': 124, 'colsample_bytree': 0.6182336908412835, 'subsample': 0.5235053813730733, 'subsample_freq': 7, 'reg_alpha': 1.120458386788827e-05, 'reg_lambda': 0.029661881116654562, 'max_bin': 270}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:43,707] Trial 21 finished with value: 3.1364461679032605 and parameters: {'n_estimators': 978, 'learning_rate': 0.22528967737214378, 'num_leaves': 61, 'max_depth': 5, 'min_child_samples': 90, 'colsample_bytree': 0.7452751816715926, 'subsample': 0.6268895275989548, 'subsample_freq': 6, 'reg_alpha': 0.0008634602053691949, 'reg_lambda': 0.010607194951968048, 'max_bin': 321}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:44,739] Trial 22 finished with value: 3.124099034941654 and parameters: {'n_estimators': 492, 'learning_rate': 0.1683538564121567, 'num_leaves': 51, 'max_depth': 3, 'min_child_samples': 64, 'colsample_bytree': 0.7077770769918449, 'subsample': 0.5184884986213496, 'subsample_freq': 5, 'reg_alpha': 0.008710005296950697, 'reg_lambda': 0.010983206764666806, 'max_bin': 311}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:48,437] Trial 23 finished with value: 3.24729400114018 and parameters: {'n_estimators': 700, 'learning_rate': 0.1540481989602641, 'num_leaves': 49, 'max_depth': 7, 'min_child_samples': 94, 'colsample_bytree': 0.6938718609975307, 'subsample': 0.5305279067898332, 'subsample_freq': 4, 'reg_alpha': 0.0001625634602750643, 'reg_lambda': 5.1636363324798005, 'max_bin': 278}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:49,712] Trial 24 finished with value: 3.475194065945035 and parameters: {'n_estimators': 361, 'learning_rate': 0.13711641488218787, 'num_leaves': 45, 'max_depth': 5, 'min_child_samples': 103, 'colsample_bytree': 0.691642596324446, 'subsample': 0.548463909178463, 'subsample_freq': 3, 'reg_alpha': 1.470046819898208e-05, 'reg_lambda': 1.5571234684506923, 'max_bin': 331}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:53,617] Trial 25 finished with value: 3.077259697249154 and parameters: {'n_estimators': 1053, 'learning_rate': 0.20578180566920298, 'num_leaves': 44, 'max_depth': 5, 'min_child_samples': 62, 'colsample_bytree': 0.6496356525528717, 'subsample': 0.5002996217863911, 'subsample_freq': 3, 'reg_alpha': 4.876847791818277e-06, 'reg_lambda': 0.0034744764569470724, 'max_bin': 330}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:55,507] Trial 26 finished with value: 3.183798523583756 and parameters: {'n_estimators': 758, 'learning_rate': 0.07483349023526417, 'num_leaves': 60, 'max_depth': 3, 'min_child_samples': 96, 'colsample_bytree': 0.7777730471571214, 'subsample': 0.578846633970185, 'subsample_freq': 2, 'reg_alpha': 0.00033482781177205246, 'reg_lambda': 0.05192135566142302, 'max_bin': 327}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:57,815] Trial 27 finished with value: 3.374250447702556 and parameters: {'n_estimators': 475, 'learning_rate': 0.08183883058612997, 'num_leaves': 45, 'max_depth': 6, 'min_child_samples': 60, 'colsample_bytree': 0.7032339793096342, 'subsample': 0.5158095251572149, 'subsample_freq': 5, 'reg_alpha': 7.790770943377627e-07, 'reg_lambda': 0.7719378057652314, 'max_bin': 316}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:28:59,510] Trial 28 finished with value: 3.0402444853226407 and parameters: {'n_estimators': 892, 'learning_rate': 0.08098379401741448, 'num_leaves': 36, 'max_depth': 3, 'min_child_samples': 119, 'colsample_bytree': 0.6099406256211426, 'subsample': 0.59303993611697, 'subsample_freq': 1, 'reg_alpha': 4.240100502990632e-05, 'reg_lambda': 0.03419637280202416, 'max_bin': 347}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:01,171] Trial 29 finished with value: 3.190985900542205 and parameters: {'n_estimators': 515, 'learning_rate': 0.18513595075581626, 'num_leaves': 67, 'max_depth': 4, 'min_child_samples': 91, 'colsample_bytree': 0.6812744238297719, 'subsample': 0.5714409759483313, 'subsample_freq': 2, 'reg_alpha': 1.82159977505683e-06, 'reg_lambda': 1.1665067469405297, 'max_bin': 343}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:02,127] Trial 30 finished with value: 3.1110368943959914 and parameters: {'n_estimators': 391, 'learning_rate': 0.15656248611371254, 'num_leaves': 56, 'max_depth': 3, 'min_child_samples': 83, 'colsample_bytree': 0.7541814526911578, 'subsample': 0.5962955843768998, 'subsample_freq': 2, 'reg_alpha': 1.1780598132989638e-07, 'reg_lambda': 0.8775794058815766, 'max_bin': 285}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:03,015] Trial 31 finished with value: 3.547805343685356 and parameters: {'n_estimators': 221, 'learning_rate': 0.1082192057881529, 'num_leaves': 51, 'max_depth': 5, 'min_child_samples': 70, 'colsample_bytree': 0.777247687603412, 'subsample': 0.5400017982361317, 'subsample_freq': 3, 'reg_alpha': 3.546899452667667e-08, 'reg_lambda': 2.042533707663056, 'max_bin': 320}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:05,106] Trial 32 finished with value: 3.089365244195883 and parameters: {'n_estimators': 771, 'learning_rate': 0.18146077376787345, 'num_leaves': 52, 'max_depth': 4, 'min_child_samples': 52, 'colsample_bytree': 0.6610559143995713, 'subsample': 0.5998775307450745, 'subsample_freq': 3, 'reg_alpha': 1.637476699005984e-06, 'reg_lambda': 3.130499010779321, 'max_bin': 307}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:06,541] Trial 33 finished with value: 3.141343845217812 and parameters: {'n_estimators': 362, 'learning_rate': 0.1802288386110993, 'num_leaves': 45, 'max_depth': 5, 'min_child_samples': 72, 'colsample_bytree': 0.7843963427519214, 'subsample': 0.580838419374689, 'subsample_freq': 4, 'reg_alpha': 3.820805405551038e-05, 'reg_lambda': 0.1609981507363254, 'max_bin': 319}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:07,505] Trial 34 finished with value: 3.1181727195646634 and parameters: {'n_estimators': 470, 'learning_rate': 0.2178771511994651, 'num_leaves': 63, 'max_depth': 3, 'min_child_samples': 57, 'colsample_bytree': 0.7666790082963444, 'subsample': 0.5066707276412378, 'subsample_freq': 5, 'reg_alpha': 2.3115477179462527e-05, 'reg_lambda': 0.02974680279657476, 'max_bin': 307}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:09,588] Trial 35 finished with value: 3.1137075265213214 and parameters: {'n_estimators': 839, 'learning_rate': 0.07620322841749694, 'num_leaves': 47, 'max_depth': 3, 'min_child_samples': 62, 'colsample_bytree': 0.6018238027432624, 'subsample': 0.6415877264834406, 'subsample_freq': 1, 'reg_alpha': 0.0022029189785177086, 'reg_lambda': 5.786655745890596, 'max_bin': 326}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:12,781] Trial 36 finished with value: 3.289206783633896 and parameters: {'n_estimators': 623, 'learning_rate': 0.06888305141845634, 'num_leaves': 48, 'max_depth': 5, 'min_child_samples': 64, 'colsample_bytree': 0.64017736863504, 'subsample': 0.5640090354808638, 'subsample_freq': 2, 'reg_alpha': 8.605155776206197e-06, 'reg_lambda': 0.020150762911907386, 'max_bin': 382}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:17,346] Trial 37 finished with value: 3.107562126501593 and parameters: {'n_estimators': 853, 'learning_rate': 0.11817534030365104, 'num_leaves': 53, 'max_depth': 4, 'min_child_samples': 107, 'colsample_bytree': 0.594464903185171, 'subsample': 0.6334389568072128, 'subsample_freq': 2, 'reg_alpha': 0.00020115899692711082, 'reg_lambda': 0.006264998372839196, 'max_bin': 379}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:19,229] Trial 38 finished with value: 3.2847749895318468 and parameters: {'n_estimators': 633, 'learning_rate': 0.1121475194429186, 'num_leaves': 53, 'max_depth': 4, 'min_child_samples': 66, 'colsample_bytree': 0.6733414849756693, 'subsample': 0.5522467292780688, 'subsample_freq': 1, 'reg_alpha': 0.029525787707566212, 'reg_lambda': 0.8311716234657998, 'max_bin': 319}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:19,980] Trial 39 finished with value: 3.3664371462390625 and parameters: {'n_estimators': 328, 'learning_rate': 0.0998664294875067, 'num_leaves': 57, 'max_depth': 3, 'min_child_samples': 73, 'colsample_bytree': 0.7158642519494002, 'subsample': 0.5180133413962191, 'subsample_freq': 4, 'reg_alpha': 5.2556917442383975e-06, 'reg_lambda': 0.06218734395901462, 'max_bin': 344}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:21,230] Trial 40 finished with value: 3.153443872958649 and parameters: {'n_estimators': 415, 'learning_rate': 0.2460417967191323, 'num_leaves': 54, 'max_depth': 4, 'min_child_samples': 92, 'colsample_bytree': 0.7773065276971685, 'subsample': 0.508708090075649, 'subsample_freq': 3, 'reg_alpha': 2.0229109676400547e-06, 'reg_lambda': 0.07674530615604695, 'max_bin': 267}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:24,512] Trial 41 finished with value: 3.040294073453971 and parameters: {'n_estimators': 1068, 'learning_rate': 0.19646823410856612, 'num_leaves': 43, 'max_depth': 4, 'min_child_samples': 70, 'colsample_bytree': 0.6660262012329461, 'subsample': 0.5622435677688133, 'subsample_freq': 4, 'reg_alpha': 7.47381118193269e-06, 'reg_lambda': 0.001337796024639006, 'max_bin': 318}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:26,539] Trial 42 finished with value: 3.085480858088881 and parameters: {'n_estimators': 744, 'learning_rate': 0.07479844207709961, 'num_leaves': 60, 'max_depth': 3, 'min_child_samples': 99, 'colsample_bytree': 0.5954871940449932, 'subsample': 0.5733468390048709, 'subsample_freq': 1, 'reg_alpha': 0.00043661178638448026, 'reg_lambda': 0.4826231096632695, 'max_bin': 355}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:30,373] Trial 43 finished with value: 3.220606102160796 and parameters: {'n_estimators': 469, 'learning_rate': 0.21908849865059116, 'num_leaves': 54, 'max_depth': 4, 'min_child_samples': 82, 'colsample_bytree': 0.6637131209756352, 'subsample': 0.5158176420267004, 'subsample_freq': 4, 'reg_alpha': 1.5479747250850846e-06, 'reg_lambda': 0.40094675284074355, 'max_bin': 342}. Best is trial 9 with value: 2.919485122730832.
[I 2026-10-01 18:29:31,645] Trial 44 finished with value: 3.160867638754606 and parameters: {'n_estimators': 503, 'learning_rate': 0.1878952427300374, 'num_leaves': 54, 'max_depth': 3, 'min_child_samples': 82, 'colsample_bytree': 0.7252356457132287, 'subsample': 0.5243563401930462, 'subsample_freq': 4, 'reg_alpha': 7.66926192778675e-07, 'reg_lambda': 9.670774189950462, 'max_bin': 303}. Best is trial 9 with value: 2.919485122730832.

Best MAPE: 2.919485122730832
Best params: {'n_estimators': 813, 'learning_rate': 0.07420147247657288, 'num_leaves': 47, 'max_depth': 3, 'min_child_samples': 66, 'colsample_bytree': 0.6520737037218487, 'subsample': 0.5369837226967138, 'subsample_freq': 1, 'reg_alpha': 0.001877106197286048, 'reg_lambda': 0.12086070524768504, 'max_bin': 354}

In [30]:
##########--------------LAST MODEL--------------##########
model_last = LGBMRegressor(
    n_estimators=813,
    learning_rate=0.07420147247657288,
    num_leaves=47,
    max_depth=3,
    min_child_samples=66,
    colsample_bytree= 0.6520737037218487,
    subsample=0.5369837226967138,
    subsample_freq= 1,
    reg_alpha=   0.001877106197286048,
    reg_lambda= 0.12086070524768504,
    objective="regression",
    random_state=42,
    importance_type="gain",
    max_bin = 354
)
model_last.fit(X_train_v3, y_train, categorical_feature=categorical_cols_v3)

predicted_ratio_last = model_last.predict(X_val_v3)
predicted_consumption_last = predicted_ratio_last * val["yearly_baseline"]

MAPE_last = ((val["consumption"] - predicted_consumption_last).abs() / val["consumption"]).mean() * 100
print("LightGBM LAST Val MAPE (%):", MAPE_last)

LightGBM LAST Val MAPE (%): 2.919485122730832

In [31]:
predicted_ratio_train_last = model_last.predict(X_train_v3)
predicted_consumption_train_last = predicted_ratio_train_last * train["yearly_baseline"]

MAPE_train_last = ((train["consumption"] - predicted_consumption_train_last).abs() / train["consumption"]).mean() * 100
print("LightGBM Train MAPE (%):", MAPE_train_last)

LightGBM Train MAPE (%): 1.5154661339466764